CREATE TABLE users(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	email TEXT NOT NULL UNIQUE,
	password TEXT,

	PRIMARY KEY(id)
);

CREATE TABLE sessions(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	user_id BIGINT NOT NULL,
	refresh_token TEXT NOT NULL UNIQUE,
	active_until TIMESTAMP WITH TIME ZONE NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX ON sessions(user_id);