CREATE TABLE users(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	email TEXT NOT NULL UNIQUE,
	password TEXT,

	PRIMARY KEY(id)
);

CREATE INDEX ON users(email);


CREATE TABLE organisations(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	name TEXT NOT NULL,

	PRIMARY KEY(id)
);


CREATE TABLE organisation_users(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	organisation_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(organisation_id) REFERENCES organisations(id) ON DELETE CASCADE,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
	UNIQUE(organisation_id, user_id)
);


CREATE TABLE sessions(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	user_id BIGINT NOT NULL,
	organisation_id BIGINT,
	refresh_token TEXT NOT NULL,
	active_until TIMESTAMP WITH TIME ZONE NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX ON sessions(user_id);